### ISSUE TITLE
om should throw if you try to put non-associative data structures into app-state

### ISSUE THREAD

**Issue by bhurlow** [omcljs/om#327]
Major om fan right here. 

The docs are pretty clear about only using associative data structures for data bound to om/root.
However, I have found that if I or a coworker accidentally adds a non-associative to app-state, the mistake isn't immediately clear and behavior can get unpredictable. 

Would it be possible for om to throw an error if you try add an incorrect data type to the app-state atom?
This would have helped my team a number of times.

**Comment by JulianLeviston** [comment]
It doesn't seem possible because your atom can be accessed outside of Om by using the normal clojure atom modification functions. You could write your own mutation function that raises errors and only use that, but I personally think it'd be easier to just remember to only use associative structures.

**Comment by bhurlow** [comment]
I suppose I could watch the atom for changes and throw appropriately

**Comment by swannodette** [comment]
Not something we're going to do.
