### ISSUE TITLE
Bug when retrieving nativeEvent whilst using advanced compilation

### ISSUE THREAD

**Issue by berendbaas** [omcljs/om#380]
I have been wrecking my brain on this trying to figure out how this could possibly be correct behaviour of the compiler, so at this point I'm assuming it's a bug. When retrieving the nativeEvent of a react event `(.-nativeEvent e)`, on simple compilation, the event is returned. When using advanced compilation however, the result is undefined. 
A sample project can be found at https://github.com/berendbaas/testbug for a proof of concept. The project.clj seems similar to the one described in the readme, so I don't think theres a problem there.

**Comment by bensu** [comment]
Hi @berendbaas 

This is not om related. The symbol `nativeEvent` is not in the [externs file](https://github.com/cljsjs/packages/blob/master/react/resources/cljsjs/react/common/react.ext.js) for React and gets munged during advanced compilation, which explains your symptoms.

You have two options:
1. Use `goog.object.get` as seen [here](https://github.com/bensu/doo/blob/master/library/src/doo/runner.cljs#L25)
2. Add the symbol to the externs file probably under `React.SyntheticEvent.prototype`

Try with 2 since it will help the rest of the community, but 1 will solve the problem now while 2 gets merged into cljsjs.
