### ISSUE TITLE
[om.next] access DOM node from within component

### ISSUE THREAD

**Issue by dvcrn** [omcljs/om#414]
In om legacy this was possible:

```clj
(defn foo [state owner]
  (reify
      om/IRender
    (render [this]
      (dom/div nil "Foo"))
      om/IDidMount
    (did-mount [_]
      (.log js/console (om/get-node owner)))))
```

In next, the following throws `Uncaught TypeError: component.getDOMNode is not a function`: 
```clj
(defui Foo
  Object
  (componentDidMount [this]
                     (.log js/console  (om/dom-node this)))
  (render [this]
          (dom/div nil "Foo")))
```

Is there a new way of accessing the DOM inside didMount?

**Comment by GetContented** [comment]
This isn't even in alpha yet.

**Comment by dvcrn** [comment]
I saw that `om/dom-node` is already there, that's why the question, or what do you mean?

**Comment by swannodette** [comment]
@GetContented this question is perfectly valid, we are in alpha.

**Comment by GetContented** [comment]
@swannodette apologies :)

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/cd508be22ce3ff8cd941cbf2a27c6e6732416772

**Comment by thheller** [comment]
I read something about this on the React Blog. I believe the intended way is now `ReactDOM.findDOMNode(this)`. Might be related to this issue?

https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

See "New Deprecations ..."

Due to the DOM node refs change mentioned above, this.getDOMNode() is now deprecated and ReactDOM.findDOMNode(this) can be used instead. Note that in most cases, calling findDOMNode is now unnecessary – see the example above in the “DOM node refs” section.

**Comment by swannodette** [comment]
@thheller in 0.14 yes, but we're not there yet. There are problems that need to be sorted out with the cljsjs/react 0.14 package first.
