### ISSUE TITLE
Path Optimization

### ISSUE THREAD

**Issue by swannodette** [omcljs/om#446]
Recursive queries can be deep and path optimization becomes more necessary. The only question is how to preserve local state modifications.

**Comment by awkay** [comment]
Wanted to write down some comments on our discussion about this topic earlier...

OK, so Falcor path optimization says I'm taking a query that I've seen before, such as

A.B[0].C.D

and noticing that I've already seen A.B[0] and it is an object that I have a ref for, so I
rewrite the query (to the server) as: 

Bref.C.D

which the server can (possibly) look up more efficiently than one that goes from the root.
Thus, I'm leveraging prior knowledge in the app cache to figure out how to elide part of
the query request (to the server).

This works because Falcor requires you to be able to do that from the ground up...anything
that is a "ref" is, by definition, findable in the data store.

In our discussion on UI path optimization (more like shouldComponentUpdate...try to avoid 
doing work on things that have not changed in the UI), we're trying to do a similar thing:
avoid doing CPU work on evaluating a portion of the query where I know that I'm updating
something that has a query whose path might pass through one or more components with
Idents.

In the original "from root" query, we've gone through and "remembered" what specific Ident
a component has given (which may or may not be an actual ref, though that seems to be the
desired convention). However, the only real requirement that we've actually stated in the general APIs is that an Ident must be client UI unique. We've said nothing about the real db structure or logic
underneath.

So there's the rub. Anything can have an Ident, but that does not mean mean the underlying
database/reads are programmed to actually look it up that way. The query from root
generates a context that is arbitrary and need not directly relate. The fact that we can *manufacture* an Ident when rendering the thing from a root query has nothing to do with our ability to easily
query on the Ident later.

Thus the desire to be able to plug in an optional optimization when we detect hot CPU paths. If the read functions can grab a subtree from the component with an Ident, then do it; otherwise just use the root query.

Under these circumstances, I think the proposed solution is a great one. If we're using something like Datascript, then it will be trivial to supply the desired optimization paths. If we're doing something else, it still won't be that challenging in many cases. It seems to me that any UI with complexity will want to write the read infrastructure in such a way as to recursively process the query, and Idents are a natural inflection point where an arbitrary sub-query can (re)start and reuse code.

If someone has written their queries/reads in such a way that the logic is already present, then there is nothing preventing them from supplying their primary read function as the read-ref function as well. If someone's underlying query processing cannot handle it that way, then as you say, they can hot-spot optimize.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/ecadae8ffb3e6ab4399882fc644dd6248c7c6c85
