### ISSUE TITLE
Routing support

### ISSUE THREAD

**Issue by swannodette** [omcljs/om#519]
Om Next could do more to provide the lego blocks for building routing solutions. `set-query!` could take the reconciler as the first argument for example. It could also take a 3rd argument of reads like `transact!` to minimize both data fetches and component re-renders.

Some thought should be put into how routers can control query parameterization.

**Comment by futuro** [comment]
What are you currently thinking about for routing architecture? How does `set-query!` factor into it? I'm currently trying to wrap my head around the problem writ large and I'm really curious about your thought process so far.

**Comment by jobez** [comment]
@futuro see https://github.com/omcljs/om/wiki/Routing-Support

**Comment by futuro** [comment]
@jobez I've read that as well, and, while it goes into slightly more detail, says roughly the same as this issue description.

What I'm trying to sort out is how changing a query for a top-level component would aid in routing, since the component has, potentially, specific code for a particular view of the data, and changing it's query would simply cause it to no longer know what to show.

Shouldn't we be altering which component is being drawn to the root instead?

**Comment by swannodette** [comment]
Please do not any noise to this issue. Thanks. When I have something to add that I think warrants discussion I will add it.

**Comment by swannodette** [comment]
People have acceptable solutions to the routing problem now. Closing.
