### ISSUE TITLE
Autocompleter example doesn't work since last wiki modification

### ISSUE THREAD

**Issue by gphilipp** [omcljs/om#597]
Since [last modification](https://github.com/omcljs/om/wiki/Remote-Synchronization-Tutorial/_compare/a30b5daea147aab26713221b3f34a725d60be372...3521dc3302e6c8b24ff811c3ffbfbc127797be3c) on the Remote Synchronization Tutorial, I can't type anything in the input box. Commenting out the `:value query` property of the input field makes it work as expected.

**Comment by swannodette** [comment]
Feel free to fix!

**Comment by peerreynders** [comment]
Deleting the ```value``` property works because according to the React documentation, ["an ```<input>``` with ```value``` set is a _controlled_ component.](https://facebook.github.io/react/docs/forms.html#controlled-components) - any user input will have no effect on the rendered element". As a result ```e.target.value``` and therefore ```query``` will only ever be an empty string.

Alternately instead of removing the preset ```value``` property, attaching the event handler to ```onChange``` instead of ```onKeyUp``` also seems to work.

```cljs
...
  (:require [goog.dom :as gdom]
            [goog.string :as gstr]
...
(defn result-item [item]
  (dom/li
    #js {:key (gstr/hashCode item)} ;; placate https://fb.me/react-warning-keys 
    item))

(defn result-list [results]
  (dom/ul #js {:key "result-list"}
    (map result-item results)))

(defn search-field [ac query]
  (dom/input
    #js {:key "search-field"
         :value query
         :onChange                  ;; this was :onKeyUp
         (fn [e]
           (om/set-query! ac
             {:params {:query (.. e -target -value)}}))}))

```
