### ISSUE TITLE
`db->tree` naively resolves idents

### ISSUE THREAD

**Issue by anmonteiro** [omcljs/om#637]
```clj
(db->tree '[[:my-route _]] {:my-route :something} {:my-route :something})
=> {:my-route :something}

whereas:

(db->tree '[[:my-route _]] {:my-route '[:something :else]} {:my-route '[:something :else]})
=> {:my-route nil}
```

**Comment by awkay** [comment]
We could use the presence of a db table as a detection mechanism for idents. E.g.:
```
[:table 1]
```
is an ident if the app state contains the key `:table`; otherwise it is simply a vector.

I see no problematic cases. There is no decent reason for app-state to contain something that **looks** like an ident unless it is pointing to something else that is already in the app state. There could be possible false-positives (e.g. the user accidentally names a table with a keyword that appears in a raw vector in their state), but such false positives are easy to avoid if you follow naming conventions.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/727438963819387f9e8269dbdd633d2076d3a3ae
