### ISSUE TITLE
set-state! results in "No queries exist for component path"

### ISSUE THREAD

**Issue by nijssels** [omcljs/om#791]
This looks like issue #687 (which is closed), but I can still get the error in a similar but simpler situation.

I get the error when updating local state of a nested component. The global state is flat.

The problem is condensed in code of the following gist [omnext_error_1.0.0-alpha46.clj](https://gist.github.com/nijssels/2aaceb3821052bdc80f52b0325598621)

Error on line 17.
![omnexterror](https://cloud.githubusercontent.com/assets/68946/18930674/561df69a-85c9-11e6-9902-baf80ab4c190.jpg)

**Comment by anmonteiro** [comment]
Given your `RootComponent`'s query, the error is expected. There is no path from `RootComponent` to `NameComponent` because you're "stealing" `NameComponent`'s query.

Here's an example query that correctly composes, and actually constructs a path (`[:name]`) from `RootComponent` to `NameComponent`:

```clj
(defui RootComponent
  static om/IQuery
  (query [this]
    [:app/title {:name (om/get-query NameComponent)}]))
``` 

I'm closing this because it's not a real issue. If you have any more questions or need any help, don't hesitate to swing by the Clojurians Slack, #om channel (you can get an invite at http://clojurians.net/)

**Comment by nijssels** [comment]
OK, got it. Already had a sneaking suspicion I did something wrong, thanks for the quick answer, one step closer in understanding om.next. And thanks for the heads up of the Slack channel, great place for further q's!
